http_port 8888

cache_mem 256 MB
maximum_object_size_in_memory 512 KB
maximum_object_size 1024 MB
cache_dir ufs /var/spool/squid 1000 16 256

access_log stdio:/dev/stdout
cache_log stdio:/dev/stdout

acl all src all
http_access allow all

via off
forwarded_for delete
request_header_access X-Forwarded-For deny all
request_header_access Via deny all
request_header_access Cache-Control deny all

refresh_pattern . 0 20% 4320
